# 通过 Github actions， 在 Github 仓库的每一次 commit 后自动同步到 Gitee 上.
name: sync2gitee

on:
  push:
    branches:
      - master
      - dev
      - main
  workflow_dispatch:  # 加上这个，就有手动运行按钮了

jobs:
  repo-sync:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # 已升级到 v4，无警告
        with:
          persist-credentials: false

      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key && env.dst_token && env.gitee_user
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/Es_Muss_S_ein'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          static_list: ${{ github.event.repository.name }}
